version: "3.7"

services:

  db:
    container_name: kepy_db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 15s
      timeout: 5s
      retries: 5
      
  redis:
    container_name: kepy_redis
    image: redis:alpine
    restart: always
    volumes:
      - "redis:/data"

  api: &api
    container_name: kepy_api
    build: .
    image: kepy_api
    command: sh -c "
      python3 manage.py migrate &&
      gunicorn kepy.wsgi -w 4 -b :5000"
    restart: always
    expose:
      - "5000"
    env_file:
      .env
    depends_on:
      db:
        condition: service_healthy
    volumes: 
      - .:/app

  celery:
    <<: *api
    container_name: kepy_celery
    image: kepy_api
    command: celery -A run_worker worker -l INFO
    restart: always

volumes:
  pgdata:
  redis: