# Generated by Django 3.2.3 on 2021-05-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('prefix', models.CharField(default='%', max_length=8)),
                ('mute_role_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('revoked', models.BooleanField(default=False)),
                ('unmute_task_id', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, default='', max_length=2048)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mute_author', to='api.discorduser')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_user', to='api.discorduser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('channel_id', models.IntegerField()),
                ('content', models.CharField(blank=True, default='', max_length=2048)),
                ('state', models.CharField(choices=[('DEFAULT', 'default'), ('EDITED', 'edit'), ('DELETED', 'deleted')], default='DEFAULT', max_length=8)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.discorduser')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guild')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.discorduser')),
            ],
        ),
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=2048)),
                ('edit_time', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.message')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=1024)),
                ('content_url', models.CharField(default='', max_length=1024)),
                ('proxy_url', models.CharField(default='', max_length=1024)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='api.message')),
            ],
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('user', 'guild'), name='unique member'),
        ),
    ]
