# Generated by Django 3.2.3 on 2021-06-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guild',
            name='mute_role_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
